### ISSUE TITLE
Music object creator

### ISSUE THREAD

**Issue by karst** [spacek531/NEDesignsObjects#22]
I don't think creating a tool that automatically writes the music. json is too difficult to make. 

This tool would need the following features:

- Convert MP3, WAV, FLAC or OGG to OGG Vorbis. 
- Fill in the following fields:
  - `<username>` : Username of the creator of the file [could be grabbed if the user is logged in if necessary] (This is required for the filename (`<username>.music.<name>.parkobj`) and ID in the same format.
  - `<name>` : Name of the song/style
  - `<authors>` : Name of the song maker, spaced with comma's.
  - `<song1/2/3>` : Name of the song 1, 2, 3, etc. depending on how many files are uploaded.
  - `<playlist en-GB/nl-NL/...>` : Display name of the playlist in en-GB (required) and other languages (optional).

**Comment by spacek531** [comment]
This feature has been implemented by Gymnasiast as a web app https://goes.rctspace.com/music
